# Generated by Django 4.2.4 on 2023-12-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminario', '0002_alter_inscrito_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='hora_inscripcion',
        ),
    ]
