# Generated by Django 4.2.4 on 2023-12-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario', '0003_remove_inscrito_hora_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='fecha_inscripcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
