# Generated by Django 4.2.4 on 2023-12-21 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seminario', '0004_alter_inscrito_fecha_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='hora_inscripcion',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
    ]
